#spring.application.name=skillgraph-backend
#
#cognodb.uri=bolt+s://db-f295b234.databases.cognodb.com
#cognodb.username=cognodb
#cognodb.password=04ff35316caccaabd9825d101f6a601b

spring.application.name=skillgraph-backend

cognodb.uri=${COGNODB_URI}
cognodb.username=${COGNODB_USERNAME:cognodb}
cognodb.password=${COGNODB_PASSWORD}